-- MySQL Script generated by MySQL Workbench
-- Sun Mar  9 12:45:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Restaurante` DEFAULT CHARACTER SET utf8 ;
USE `Restaurante` ;

-- -----------------------------------------------------
-- Table `Restaurante`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`Mesa` (
  `mesa_id` INT NOT NULL,
  `lugar` VARCHAR(255) NULL,
  PRIMARY KEY (`mesa_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Mesero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`Mesero` (
  `mesero_id` INT NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `contacto_no` VARCHAR(10) NULL,
  `shift` VARCHAR(10) NULL,
  PRIMARY KEY (`mesero_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Pedido_Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`Pedido_Mesa` (
  `pedido_id` INT NOT NULL,
  `fecha_hora` VARCHAR(45) NOT NULL,
  `mesa_id` INT NULL,
  `mesero_id` INT NULL,
  PRIMARY KEY (`pedido_id`),
  INDEX `fk_Tabla_pedido_1_idx` (`mesero_id` ASC) VISIBLE,
  INDEX `fk_Tabla_pedido_2_idx` (`mesa_id` ASC) VISIBLE,
  CONSTRAINT `fk_Tabla_pedido_1`
    FOREIGN KEY (`mesero_id`)
    REFERENCES `Restaurante`.`Mesero` (`mesero_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tabla_pedido_2`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `Restaurante`.`Mesa` (`mesa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`Cliente` (
  `cliente_id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `NIC_no` VARCHAR(12) NULL,
  `contacto_no` VARCHAR(10) NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Reservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`Reservacion` (
  `reservacion_id` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `no_invitados` INT NULL,
  `pedido_id` INT NULL,
  `mesa_id` INT NULL,
  `cliente_id` INT NULL,
  PRIMARY KEY (`reservacion_id`),
  INDEX `fk_Reservacion_2_idx` (`mesa_id` ASC) VISIBLE,
  INDEX `fk_Reservacion_3_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reservacion_1`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `Restaurante`.`Pedido_Mesa` (`pedido_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservacion_2`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `Restaurante`.`Mesa` (`mesa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservacion_3`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `Restaurante`.`Cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`Menu` (
  `menu_id` INT NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `disponibilidad` INT NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Menu_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`Menu_item` (
  `menu_item_id` INT NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `precio` FLOAT NULL,
  `disponibilidad` INT NULL,
  `menu_id` INT NULL,
  PRIMARY KEY (`menu_item_id`),
  INDEX `fk_Menu_item_1_idx` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_item_1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `Restaurante`.`Menu` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Pedido_Menu_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`Pedido_Menu_Item` (
  `pedido_id` INT NOT NULL,
  `menu_item_id` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`pedido_id`, `menu_item_id`),
  INDEX `fk_Pedido_Menu_Item_2_idx` (`menu_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Menu_Item_1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `Restaurante`.`Pedido_Mesa` (`pedido_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Menu_Item_2`
    FOREIGN KEY (`menu_item_id`)
    REFERENCES `Restaurante`.`Menu_item` (`menu_item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
